services:
  app:
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=sample
      - MYSQL_USER=superman
      - MYSQL_PASSWORD=password